"""empty message

Revision ID: 03bd66aa93eb
Revises: 7b43feccb506
Create Date: 2023-01-21 23:37:47.760925

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03bd66aa93eb'
down_revision = '7b43feccb506'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card', sa.Column('faction_id', sa.Integer(), nullable=True))
    op.drop_constraint('card_faction_fkey', 'card', type_='foreignkey')
    op.create_foreign_key(None, 'card', 'faction', ['faction_id'], ['id'])
    op.drop_column('card', 'faction')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card', sa.Column('faction', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'card', type_='foreignkey')
    op.create_foreign_key('card_faction_fkey', 'card', 'faction', ['faction'], ['id'])
    op.drop_column('card', 'faction_id')
    # ### end Alembic commands ###
