"""empty message

Revision ID: 213a090c22ef
Revises: 311473b75276
Create Date: 2023-01-21 21:56:47.054936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '213a090c22ef'
down_revision = '311473b75276'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
