"""empty message

Revision ID: 311473b75276
Revises: ee9969fd2edf
Create Date: 2023-01-20 22:46:16.534021

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '311473b75276'
down_revision = 'ee9969fd2edf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('color',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_color_id'), 'color', ['id'], unique=False)
    op.create_table('faction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_faction_id'), 'faction', ['id'], unique=False)
    op.create_table('type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_type_id'), 'type', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_type_id'), table_name='type')
    op.drop_table('type')
    op.drop_index(op.f('ix_faction_id'), table_name='faction')
    op.drop_table('faction')
    op.drop_index(op.f('ix_color_id'), table_name='color')
    op.drop_table('color')
    # ### end Alembic commands ###
