"""empty message

Revision ID: b6bad88064da
Revises: 03bd66aa93eb
Create Date: 2023-01-21 23:46:49.894546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6bad88064da'
down_revision = '03bd66aa93eb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
