"""empty message

Revision ID: e7e8b234349f
Revises: b6bad88064da
Create Date: 2023-01-22 10:33:22.509249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7e8b234349f'
down_revision = 'b6bad88064da'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card', sa.Column('type_id', sa.Integer(), nullable=True))
    op.drop_constraint('card_type_fkey', 'card', type_='foreignkey')
    op.create_foreign_key(None, 'card', 'type', ['type_id'], ['id'])
    op.drop_column('card', 'type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card', sa.Column('type', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'card', type_='foreignkey')
    op.create_foreign_key('card_type_fkey', 'card', 'type', ['type'], ['id'])
    op.drop_column('card', 'type_id')
    # ### end Alembic commands ###
