"""empty message

Revision ID: ee9969fd2edf
Revises: 8bc770fd85c7
Create Date: 2023-01-20 22:39:07.258675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee9969fd2edf'
down_revision = '8bc770fd85c7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
